using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Alchemy
{
    static partial class AlchemyResources
    {
        public static class UI
        {
            private static Dictionary<int, string[]> m_uiresources =
                new Dictionary<int, string[]>();
		
			public static class Indexes
			{
				public const int NonTerminalsHint = 0;
				public const int NonTerminalsSearchHint = 1;
				public const int TerminalsHint = 2;
				public const int ButtonHint = 3;
				public const int ButtonWiki = 4;
				public const int ButtonMore = 5;
				public const int ButtonHelp = 6;
				public const int ButtonAbout = 7;
				public const int DesktopHint = 8;
				public const int TrashHint = 9;
				public const int HelpTitle = 10;
				public const int HelpLine1 = 11;
				public const int HelpLine2 = 12;
				public const int HelpLine3 = 13;
				public const int HelpLine4 = 14;
				public const int AboutTitle = 15;
				public const int AboutLine1 = 16;
				public const int AboutLine2 = 17;
				public const int AboutLine3 = 18;
				public const int AboutLine4 = 19;
				public const int AboutLine5 = 20;
				public const int CheatTitle = 21;
				public const int HintTitle = 22;
				public const int HintDescription = 23;
				public const int HintFrom = 24;
				public const int HintClose = 25;
				public const int LanguageTitle = 26;
				public const int LanguageDescription = 27;
				public const int LanguageButton = 28;
				public const int HeaderSaves = 29;
				public const int HeaderLanguage = 30;
				public const int HeaderSettings = 31;
				public const int HeaderCheats = 32;
				public const int HeaderCredits = 33;
				public const int SavesInfoLine = 34;
				public const int ButtonSave = 35;
				public const int ButtonLoad = 36;
				public const int ButtonReset = 37;
				public const int SettingCombineNew = 38;
				public const int SettingTapCombine = 39;
				public const int MoreTitle = 40;
				public const int ResetProgressWarning = 41;
				public const int ShowTimer = 42;
				public const int DesktopHint2 = 43;
				public const int DesktopHint3 = 44;
				public const int DesktopHint4 = 45;
				public const int DesktopHint5 = 46;
				public const int DesktopHint6 = 47;
				public const int ElementsListHint1 = 48;
				public const int ElementsListHint2 = 49;
				public const int ElementsListHint3 = 50;
				public const int ElementsListHint4 = 51;
				public const int ButtonClear = 52;
				public const int VictoryTitle = 53;
				public const int VictoryCongrats = 54;
				public const int VictoryDescription = 55;
			
			}
			
			#region properties
			public static string NonTerminalsHint { get { return m_uiresources[Languages.CurrentLanguage][Indexes.NonTerminalsHint];}}
			public static string NonTerminalsSearchHint { get { return m_uiresources[Languages.CurrentLanguage][Indexes.NonTerminalsSearchHint];}}
			public static string TerminalsHint { get { return m_uiresources[Languages.CurrentLanguage][Indexes.TerminalsHint];}}
			public static string ButtonHint { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ButtonHint];}}
			public static string ButtonWiki { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ButtonWiki];}}
			public static string ButtonMore { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ButtonMore];}}
			public static string ButtonHelp { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ButtonHelp];}}
			public static string ButtonAbout { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ButtonAbout];}}
			public static string DesktopHint { get { return m_uiresources[Languages.CurrentLanguage][Indexes.DesktopHint];}}
			public static string TrashHint { get { return m_uiresources[Languages.CurrentLanguage][Indexes.TrashHint];}}
			public static string HelpTitle { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HelpTitle];}}
			public static string HelpLine1 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HelpLine1];}}
			public static string HelpLine2 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HelpLine2];}}
			public static string HelpLine3 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HelpLine3];}}
			public static string HelpLine4 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HelpLine4];}}
			public static string AboutTitle { get { return m_uiresources[Languages.CurrentLanguage][Indexes.AboutTitle];}}
			public static string AboutLine1 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.AboutLine1];}}
			public static string AboutLine2 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.AboutLine2];}}
			public static string AboutLine3 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.AboutLine3];}}
			public static string AboutLine4 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.AboutLine4];}}
			public static string AboutLine5 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.AboutLine5];}}
			public static string CheatTitle { get { return m_uiresources[Languages.CurrentLanguage][Indexes.CheatTitle];}}
			public static string HintTitle { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HintTitle];}}
			public static string HintDescription { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HintDescription];}}
			public static string HintFrom { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HintFrom];}}
			public static string HintClose { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HintClose];}}
			public static string LanguageTitle { get { return m_uiresources[Languages.CurrentLanguage][Indexes.LanguageTitle];}}
			public static string LanguageDescription { get { return m_uiresources[Languages.CurrentLanguage][Indexes.LanguageDescription];}}
			public static string LanguageButton { get { return m_uiresources[Languages.CurrentLanguage][Indexes.LanguageButton];}}
			public static string HeaderSaves { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HeaderSaves];}}
			public static string HeaderLanguage { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HeaderLanguage];}}
			public static string HeaderSettings { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HeaderSettings];}}
			public static string HeaderCheats { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HeaderCheats];}}
			public static string HeaderCredits { get { return m_uiresources[Languages.CurrentLanguage][Indexes.HeaderCredits];}}
			public static string SavesInfoLine { get { return m_uiresources[Languages.CurrentLanguage][Indexes.SavesInfoLine];}}
			public static string ButtonSave { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ButtonSave];}}
			public static string ButtonLoad { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ButtonLoad];}}
			public static string ButtonReset { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ButtonReset];}}
			public static string SettingCombineNew { get { return m_uiresources[Languages.CurrentLanguage][Indexes.SettingCombineNew];}}
			public static string SettingTapCombine { get { return m_uiresources[Languages.CurrentLanguage][Indexes.SettingTapCombine];}}
			public static string MoreTitle { get { return m_uiresources[Languages.CurrentLanguage][Indexes.MoreTitle];}}
			public static string ResetProgressWarning { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ResetProgressWarning];}}
			public static string ShowTimer { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ShowTimer];}}
			public static string DesktopHint2 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.DesktopHint2];}}
			public static string DesktopHint3 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.DesktopHint3];}}
			public static string DesktopHint4 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.DesktopHint4];}}
			public static string DesktopHint5 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.DesktopHint5];}}
			public static string DesktopHint6 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.DesktopHint6];}}
			public static string ElementsListHint1 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ElementsListHint1];}}
			public static string ElementsListHint2 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ElementsListHint2];}}
			public static string ElementsListHint3 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ElementsListHint3];}}
			public static string ElementsListHint4 { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ElementsListHint4];}}
			public static string ButtonClear { get { return m_uiresources[Languages.CurrentLanguage][Indexes.ButtonClear];}}
			public static string VictoryTitle { get { return m_uiresources[Languages.CurrentLanguage][Indexes.VictoryTitle];}}
			public static string VictoryCongrats { get { return m_uiresources[Languages.CurrentLanguage][Indexes.VictoryCongrats];}}
			public static string VictoryDescription { get { return m_uiresources[Languages.CurrentLanguage][Indexes.VictoryDescription];}}
			#endregion
				
            static UI()
            {
				m_uiresources[Languages.Indexes.Czech] = new string[]
				{
					"Dostupné objevy {0}/{1}",
					"Vyhledejte element",
					"Konečný element",
					"Rada",
					"Wiki",
					"Více",
					"Pomoc",
					"O aplikaci",
					"Sem přetáhni element pro kombinaci",
					"Sem přetáhni element pro odstranění",
					"Pomoc",
					"Začínáš se čtyřmi základními elementy: ohněm, vzduchem, vodou a zemí. Jejich kombinací získáč další elementy. Hra je u konce, pokud jsou objeveny všechny elementy.\n\n",
					"Můžeš přetáhnout elementy z levého panelu do centrální části (pracovní plochu). Přetahuj dva elementy na sebe a tím je kombinuj. Některé elementy jsou konečné. Takové již nelze kombinovat. jsou zobrazeny v druhém panelu a nelze je přetáhnout do střední části. Element lze také přidat dvouklikem na seznam elementů.\n\n",
					"Pro odstranění elementu z pracovní plochy jej přetáhněte na popelnici. Pro odstranění všech elementů z pracovní plochy dvouklikněte na popelnici. Elementy můžete vymazat také vybráním elementu myší spolu s klávesou CTRL a poté stisknutím klávesy Delete.\n\n",
					"Dvouklikněte na element z pracovní plochy pro jeho kopii. Kvouklikem na volné místo pracovní plochy budou přidány čtyři základní elementy. \n\n",
					"O Alchemy",
					"Alchemy {0} pro Windows\n",
					"Autor: Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Navštivte www.mariusbancila.ro\n",
					"Inspirováno Alchemy pro Android od Andrey Zaikin",
					"Zobrazit všechny dostupné elementy",
					"Rada",
					"Zkuste vytvořit",
					"z",
					"Klikněte do plochy pro zavření okna",
					"Jazyk",
					"Zvolte jazyk",
					"Vybrat {0} jako nový jazyk",
					"Uložené",
					"Jazyk",
					"Nastavení",
					"Cheats",
					"Kredit",
					"Vaše hra je automaticky uložena při ukončení aplikace. Hra se znovu nahraje při startu aplikace.\n\nJe možné si hru uložit a znovu načíst z jiného než základního souboru.\n\nJe také možné hru zresetovat a začít znovu.\n",
					"Uložit",
					"Nahrát",
					"Reset",
					"Kombinovat jen nové (ignoruj již vynalezené kombinace)",
					"Kombinuj kliknutím (nepřetahovat, kliknout na první, a pak druhý element)",
					"Více možností",
					"Skutečně chcete aby se Váš současný pokrok zcela vymazal? Jste si jisti?\n\nJe doporučeno nejprve uložit aktuální stav, než provedete reset.\n\nSkutečně resetovat?",
					"Zobrazit časomíru (celkový uplynulý čas)",
					"Klikni na Vymazat pro odstranění všech",
					"Ctrl + kliknití + Delete pro vymazání elementu",
					"Dvouklik na element pro jeho zdvojení",
					"Dvouklik na plochu pro základní elementy",
					"Použíj tlačítko Více pro nastavení",
					"Dvouklikem přidáte na plochu",
					"Chytni a přetáhni na plochu",
					"Některé elementy nelze kombinovat",
					"Zadej jménu pro filtrování seznamu",
					"Vymazat",
					"Vítězství",
					"Gratuluji!",
					"Vynalezl jsi všechny dostupné elementy!",
				};
				
				m_uiresources[Languages.Indexes.Danish] = new string[]
				{
					"Fundne elementer {0}/{1}",
					"Skriv her for at filtrere elementer",
					"Slutelementer",
					"Hint",
					"Wiki",
					"Mere",
					"Hjælp",
					"Om",
					"Træk elementer her for at kombinere",
					"Træk elementer her for at slette",
					"Hjælp",
					"Du starter med fire basale elementer: ild, luft, vand og jord. Kombiner dem for at få nye elementer. Du er færdig når du finder alle elementerne.\n\n",
					"Du kan trække elementer fra det venstre panel ind i det centrale område. Træk to elementer sammen for at kombinere dem. Visse elementer er slutelementer, de kan ikke kombineres mere. De er vist i et andet panel og kan ikke trækkes ind på skrivebordsområdet. Du kan også tilføje elementer fra listen til skrivebordet ved at dobbeltklikke på dem.\n\n",
					"For at slette et element fra skrivebordet, træk det i skraldespanden. For at fjerne alle elementer fra skrivebordet, dobbeltklik på skraldespanden. Du kan også slette elementer ved at vælge dem med musen mens du holder Ctrl nede og derefter trykker Delete.\n\n",
					"Dobbeltklik på et element på skrivebordet for at fordoble det. Dobbeltklik på et tomt område af skrivebordet for at få de fire basale elementer.\n\n",
					"Om Alchemy",
					"Alchemy {0} til Windows\n",
					"Kreeret af Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Besøg på www.mariusbancila.ro\n",
					"Inspireret af Alchemy til Android af Andrey Zaikin",
					"Vis alle tilgængelige elementer",
					"Hints",
					"Trøv at lave",
					"Fra",
					"Klik i hint vinduet for at lukke det",
					"Sprog",
					"Vælg sprog",
					"Vælg {0} som nyt sprog",
					"Gemte",
					"Sprog",
					"Indstillinger",
					"Snyd",
					"Credits",
					"Dit fremskridt i spillet bliver gemt automatisk når du lukker spillet og hentet når du åbner det.\n\nDu kan gemme eller hente fremskridt til eller fra andre filer end standarden.\n\nDu kan også nulstille dit fremskridt og starte helt forfra.\n",
					"Gem",
					"Hent",
					"Start forfra",
					"Kombiner kun nye (ignorer allerede fundne kombinationer)",
					"Klik for at kombinere (ikke træk, klik på første element og derefter på andet)",
					"Flere indstillinger",
					"Du er ved at slette hele dit fremskridt. Er du sikker på at du vil gøre det?\n\nDet anbefales at du gemmer dit fremskridt før du nulstiller.\n\nVil du nulstille?",
					"Vis ur (Totalt forløbet tid)",
					"Klik her for at slette alt",
					"Ctrl + museklik + Delete for at slette et element",
					"Dobbeltklik på et element for at fordoble det",
					"Dobbeltklik på desktoppen for de basale elementer",
					"Brug knappen Mere for indstillinger",
					"Dobbeltklik for at tilføje til desktoppen",
					"Træk og slip til desktoppen",
					"Visse elementer kan ikke kombineres",
					"Skriv et navn for at filtrere listen",
					"Ryd",
					"Sejr",
					"Lykønskninger!",
					"Du har fundet alle tilgængelige elementer!",
				};
				
				m_uiresources[Languages.Indexes.Dutch] = new string[]
				{
					"Gevonden elementen {0}/{1}",
					"Elementen filteren",
					"Eind elementen",
					"Hint",
					"Wiki",
					"Meer",
					"Help",
					"Over",
					"Elementen hierheen slepen om te combineren",
					"Elementen hierheen slepen om te verwijderen",
					"Help",
					"Je start met vier basis elementen: vuur, lucht, water en aarde. Combineer ze om nieuwe elementen te verkrijgen. Je bent klaar als je alle elementen hebt gevonden.\n\n",
					"Gevonden elementen worden getoont op het middenscherm en op het linkerscherm. Om een gevonden element terug te krijgen op het middenscherm kan je deze simpel vanuit het linkerscherm slepen naar het middenscherm (of dubbelklikken). Sommige elementen zijn eind elementen en kunnen niet meer worden gecombineerd. Deze zijn te herkennen aan het rode stopteken op het element.Deze elementen zijn niet meer naar het midden te slepen. \n\n",
					"Om alle elementen van het middenscherm te verwijderen klik je op de wissen knop. Om één of meerdere elementen te wissen houd je de ctrl toets ingedrukt terwijl je klikt op de elementen die je van het middenscherm wil verwijderen. Klik vervolgens op de delete toets. .\n\n",
					"Dubbelklik op een element in het middenscherm om te kopieëren. Dubbelklik op een lege plaats van het middenscherm om de vier basiselementen te verkrijgen.\n\n",
					"Over Alchemy",
					"Alchemy {0} voor Windows\n",
					"Ontworpen by Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Bezoek mij op www.mariusbancila.ro\n",
					"Geïnspireerd door Alchemy voor Android door Andrey Zaikin",
					"Toon alle beschikbare elementen",
					"Hints",
					"Probeer",
					"te maken van",
					"Klik binnen scherm om te sluiten",
					"Taal",
					"Selecteer taal",
					"Selecteer {0} als nieuwe taal",
					"Opslaan",
					"Taal",
					"Instellingen",
					"Cheats",
					"Credits",
					"Het spel word automatisch opgeslagen als je afsluit en geladen als je start.\n\nJe kan opslaan en laden van een andere lokatie dan standaard.\n\nJe kan ook het gehele spel resetten en opnieuw beginnen.\n",
					"Opslaan",
					"Laden",
					"Reset",
					"Alleen nieuwe elementen combineren (negeer reeds gevonden elementen)",
					"Klik om te combineren (niet slepen, klik op 1ste element, dan op 2de element)",
					"Meer opties",
					"Je staat op het punt om al je gevonden elementen te verwijderen. Weet je het zeker?\n\nHet is aanbevolen om eerst je huidige gevonden elementen op te slaan.\n\nGevonden elementen wissen??",
					"Toon Speeltijd (totaal verstreken tijd)",
					"Klik op wissen om alle elementen te verwijderen",
					"Ctrl + muisklik + Delete om één element te verwijderen",
					"Dubbelklik op element om deze te kopieëren",
					"Dubbelklik op scherm om basiselementen te verkrijgen",
					"Gebruik knop meer voor instellingen",
					"Dubbelklikken om op hoofdscherm te zetten",
					"Sleep naar hoofdscherm",
					"Sommige elementen zijn niet te combineren",
					"Type een naam om te filteren",
					"Wissen",
					"Overwinning",
					"Gefeliciteerd !",
					"Je hebt alle elementen gevonden !",
				};
				
				m_uiresources[Languages.Indexes.English] = new string[]
				{
					"Unlocked elements {0}/{1}",
					"Type here to filter elements",
					"Terminal elements",
					"Hint",
					"Wiki",
					"More",
					"Help",
					"About",
					"Drag elements here to combine",
					"Drag element here to remove",
					"Help",
					"You start with four basic elements: fire, air, water and earth. Combine them to obtain new elements. You are finished when you unlock all the elements.\n\n",
					"You can drag elements from the left panel into the central area. Drag two elements together to combine them. Some elements are terminals, they cannot be combined any more. They are shown with a blocking icon and cannot be dragged on the desktop area. You can also add elements from the list to the desktop by double clicking on them.\n\n",
					"To remove all the elements from the desktop double click on the trash. You can also delete elements by selecting them with the mouse while holding the Control key down and then pressing Delete.\n\n",
					"Double click on an element on the desktop to multiply it. Double click on an empty space on the desktop to bring forth the four basic elements.\n\n",
					"About Alchemy",
					"Alchemy {0} for Windows\n",
					"Created by Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Visit at www.mariusbancila.ro\n",
					"Inspired by Alchemy for Android by Andrey Zaikin",
					"Show all available elements",
					"Hints",
					"Try to make",
					"From",
					"Click inside to close the tip window",
					"Language",
					"Select language",
					"Select {0} as new language",
					"Saves",
					"Language",
					"Settings",
					"Cheats",
					"Credits",
					"Your game progress is saved automatically when you close the game and loaded when you start.\n\nYou can store or load the progress to or from other file than the default.\n\nYou can also reset your entire progress and start all over.\n",
					"Save",
					"Load",
					"Reset",
					"Combine only new (ignore already discovered combinations)",
					"Tap to combine (don't drag, tap on 1st element and then on 2nd)",
					"More options",
					"You are about to delete your entire progress so far. Are you sure you want to do that?\n\nIt is recommended that you save your current progress before resetting.\n\nDo you want to reset?",
					"Display timer (total elapsed time)",
					"Click on Clear to delete all",
					"Ctrl + mouse click + Delete to delete an element",
					"Double click on element to double it",
					"Double click on desktop for basic elements",
					"Use button More for settings",
					"Double click to put on desktop",
					"Drag and drop to desktop",
					"Some elements cannot be combined",
					"Type a name to filter the list",
					"Clear",
					"Victory",
					"Congratulations!",
					"You have unlocked all the available elements!",
				};
				
				m_uiresources[Languages.Indexes.French] = new string[]
				{
					"Eléments débloqués {0}/{1}",
					"Tapez ici pour filtrer les éléments",
					"Eléments Aboutis",
					"Indice",
					"Wiki",
					"Plus",
					"Aide",
					"A propos",
					"Déposez les éléments ici pour les combiner",
					"Déposez les éléments ici pour les supprimer",
					"Aide",
					"Tu commences avec quatre éléments basiques : le feu, l'air, l'eau et la terre. Combine les pour obtenir de nouveaux éléments. Tu as gagné quand tu as débloqué tous les éléments.\n\n",
					"Vous pouvez déplacer les éléments de la réserve à gauche dans la zone centrale. Superposez deux éléments pour les combiner. Certains éléments sont aboutis, ils ne peuvent plus être combinés. Ils sont visibles dans la seconde réserve mais ne peuvent pas être déplacés dans la zone centrale. Vous pouvez aussi ajouter des éléments à la zone centrale en double-cliquant dessus.\n\n",
					"Pour retirer un éléments de la zone centrale, déplacez le sur la corbeille. Pour retirer tous les éléments de la zone centrale, double-cliquez sur la réserve. Vous pouvez aussi supprimer un élément en le selectionnant avec la souris tout en appuyant sur Controle et Supprimer.\n\n",
					"Double-cliquez sur un élément de la zone centrale pour le multiplier. Double-cliquez sur un espace vide de la zone centrale pour y ajouter les quatre éléments de base.\n\n",
					"A propos de Alchemy",
					"Alchemy {0} pour Windows\n",
					"Créé par Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Visitez www.mariusbancila.ro\n",
					"Inspiré de Alchemy pour Android par Andrey Zaikin",
					"Montrer tous les éléments disponibles",
					"Indices",
					"Essayez de créer",
					"A partir de",
					"Cliquez pour fermer la fenêtre",
					"Langue",
					"Selectionnez une language",
					"Selectionner {0} comme nouvelle language",
					"Sauvegarder",
					"Langues",
					"Réglages",
					"Tricher",
					"Crédits",
					"Votre progression dans le jeu est automatiquement sauvegardée quand vous fermez le jeu et chargée quand vous l'ouvrez.\n\nVous pouvez enregistrer ou charger votre progression vers ou depuis un autre fichier que celui par défaut.\n\nVous pouvez aussi réinitialiser votre progression et tout recommencer.\n",
					"Sauvegarder",
					"Charger",
					"Réinitialiser",
					"Combiner seulement les nouveautés (Ignore les combinaisons déjà découvertes)",
					"Sélectionner pour combiner (ne déplacez plus, sélectionnez le premier élément puis le deuxième)",
					"Plus d'options",
					"Vous êtes sur le point de supprimer toute votre progression jusqu'ici. Etes-vous sûr de vouloir le faire ?\n\nIl est recommandé de sauvegardé votre progression actuelle avant de réinitialiser.\n\nVoulez-vous réinitialiser?",
					"Temps de jeu (temps total écoulé)",
					"Clique sur effacer pour tout supprimer",
					"Ctrl + clique souris + suppr pour supprimer un élément",
					"Double clique sur un élément pour le dédoubler",
					"Double clique sur la fenêtre centrale pour obtenir les éléments basiques",
					"Utilise le bouton Plus pour les options",
					"Double clique pour mettre dans la fenêtre centrale",
					"Fais glisser et lâche sur la fenêtre centrale",
					"Certains éléments ne peuvent pas être combinés",
					"Tape un mot pour filtrer la liste.",
					"Effacer",
					"Victory",
					"Congratulations!",
					"You have unlocked all the available elements!",
				};
				
				m_uiresources[Languages.Indexes.German] = new string[]
				{
					"Freigespielte Elemente {0}/{1}",
					"Elemente suchen",
					"Finale Elemente",
					"Hinweis",
					"Wiki",
					"Weitere",
					"Hilfe",
					"Info",
					"Zum Kombinieren Elemente hierher ziehen",
					"Zum Entfernen Element hierher ziehen",
					"Hilfe",
					"Du beginnst mit vier Grundelementen: Feuer, Luft, Wasser und Erde. Kombiniere sie um neue Elemente zu erhalten. Das Spiel endet, wenn du alle Elemente entdeckt hast.\n\n",
					"Du kannst Elemente aus dem linken Fenster in die mittlere Arbeitsfläche ziehen. Ziehe dort zwei Elemente übereinander um sie zu kombinieren. Einige Elemente sind finale Elemente, d.h. sie können nicht mehr kombiniert werden. Sie werden unten links angezeigt und können nicht in den Arbeitsbereich gezogen werden. Elemente aus der Liste können auch durch einen Doppelklick dem Arbeitsbereich hinzugefügt werden.\n\n",
					"Um ein Element vom Desktop zu entfernen, ziehe es einfach über den Papierkorb. Um alle Elemente vom Desktop zu entfernen reicht ein Doppelklick auf den Papierkorb. Man kann auch mehrere Elemente löschen, indem man sie mit der Maus auswählt und gleichzeitig die STRG-Taste gedrückt hält. Danach die Entfernen-Taste drücken.\n\n",
					"Doppelklicke auf ein Element im Arbeitsbereich um es zu duplizieren. Ein Doppelklick auf einen leeren Bereich des Desktops erzeugt die vier Grundelemente.\n\n",
					"Über Alchemy",
					"Alchemy {0} für Windows\n",
					"Autor: Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Webseite: www.mariusbancila.ro\n",
					"Inspiriert von Alchemy für Android von Andrey Zaikin",
					"Zeige alle erhältlichen Elemente",
					"Hinweise",
					"Versuche herzustellen:",
					"aus",
					"Hineinklicken um das Hinweisfenster zu schließen",
					"Sprache",
					"Sprache wählen",
					"Wähle {0} als neue Sprache",
					"Gespeichert",
					"Sprache",
					"Einstellungen",
					"Cheats",
					"Danksagung",
					"Der Spielstand wird automatisch gespeichert wenn das Spiel beendet wird. Beim erneuten Öffnen wird es wieder geladen.\n\nDer Fortschritt kann auch in eine andere Datei gespeichert bzw. von einer anderen Datei geladen werden als von der Default-Datei.\n\nEs ist auch möglich den Spielstand zurückzusetzen und von vorne zu beginnen.\n",
					"Speichern",
					"Laden",
					"Reset",
					"Nur neue Elemente kombinieren (bereits entdeckte Verbindungen ignorieren)",
					"Durch Klicken kombinieren (nicht ziehen, erstes Element anklicken und dann Zweites.)",
					"Mehr Optionen",
					"Du bist gerade dabei den gesamten bisherigen Spielstand zu löschen. Bist du sicher?\n\nEs wird empfohlen, dass du vor dem Reset den aktuellen Zustand speicherst.\n\nWirklich zurücksetzen?",
					"Timer anzeigen (gesamte Spielzeit)",
					"Klicken Sie auf Löschen, um alle löschen",
					"Ctrl + mausklick + Delete auf ein Element löschen",
					"Doppelklicken Sie auf Element klicken, um es doppelt",
					"Doppelklicken Sie auf dem Desktop für Grundelemente",
					"Mit der Taste Weitere für die Einstellungen",
					"Doppelklicken Sie auf Desktop bringen",
					"Drag & Drop auf den Desktop",
					"Einige Elemente können nicht kombiniert werden",
					"Geben Sie einen Namen für die Liste filtern",
					"Löschen",
					"Victory",
					"Congratulations!",
					"You have unlocked all the available elements!",
				};
				
				m_uiresources[Languages.Indexes.Hebrew] = new string[]
				{
					"אלמנטים זמינים {1}/{0}",
					"הקלד כאן על מנת לסנן אלמנטים",
					"אלמנטים סופיים",
					"רמז",
					"Wiki",
					"עוד",
					"עזרה",
					"אודות",
					"גרור אלמנטים לכאן על מנת לשלבם",
					"גרור אלמנטים לכאן על מנת למחוק",
					"עזרה",
					"התחל עם ארבעה אלמנטים בסיסיים: אש, אוויר, מים ואדמה. שלב ביניהם על מנת ליצור אלמנטים חדשים. המשחק מסתיים כאשר נמצאו כל האלמנטים.\n\n",
					"יש לגרור אלמנטים מהפאנל השמאלי לפאנל המרכזי - שולחן העבודה. גרור שתי אלמנטים אחד על השני על מנת לשלבם. ישנם אלמנטים סופיים, אותם לא ניתן לשלב עוד, הם מופיעים בפאנל השמאלי התחתון. ניתן להוסיף אלמנטים לשולחן העבודה על ידי לחיצה כפולה עליהם.\n\n",
					"כדי לנקות את שולחן העבודה מכל האלמנטים יש ללחוץ לחיצה כפולה על סימן פח האשפה.\n\n",
					"לחיצה כפולה על אלמנט תשכפל אותו, לחיצה כפולה על שטח ריק בשולחן העבודה תוסיף את ארבעת האלמנטים הבסיסיים.\n\n",
					"אודות אלכימיה",
					"Alchemy {0} for Windows\n",
					"Created by Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Visit at www.mariusbancila.ro\n",
					"Inspired by Alchemy for Android by Andrey Zaikin",
					"הצג את כל האלמנטים הקיימים",
					"רמזים",
					"נסה ליצור",
					"מ",
					"הקש על מנת לסגור את חלון הטיפים",
					"שפה",
					"בחר שפה",
					"בחר {0} כשפה חדשה",
					"שמורים",
					"שפה",
					"הגדרות",
					"צ'יטים",
					"תודות",
					"\nהמשחק נשמר באופן אוטומטי בעת היציאה.\n\nניתן לטעון משחק מקובץ שנשמר במעוד מועד.\n\nניתן לאפס את המשחק ולהתחיל מחדש.",
					"שמירה",
					"טעינה",
					"איפוס",
					"שלב רק אלמנטים חדשים (התעלם מאלמנטים שכבר גיליתי)",
					"לחץ כדי לשלב (אל תגרור, לחץ על אלמנט ראשון ואז על האלמנט השני)",
					"אפשרויות נוספות",
					"אתה עומד לאפס את התקדמותך עד לשלב זה. האם אתה בטוח שברצונך לבצע פעולה זו?\n\nמומלץ לשמור את התקדמותך לפני האיפוס.\n\nהאם ברצונך לאפס?",
					"הצג טיימר",
					"לחץ על איזור ריק כדי לנקות הכל",
					"החזק את לחצן ctrl ואז לחץ על אלמנט על מנת למחוק אותו.",
					"לחץ לחיצה כפולה על אלמנט כדי לשכפלו.",
					"לחץ לחיצה כפולה על שולחן העבודה כדי להציג את האלמנטים הבסיסיים.",
					"לחץ על לחצן עוד להגדרות נוספות",
					"לחיצה כפולה כדי להעביר לשולחן עבודה",
					"גרור לשולחן העבודה",
					"ישנם אלמנטים שלא ניתן לשלב",
					"הקש מילה כדי לסנן את הרשימה",
					"נקה",
					"ניצחת!",
					"מזל טוב!",
					"מצאת את כל האלמנטים האפשריים!",
				};
				
				m_uiresources[Languages.Indexes.Hungarian] = new string[]
				{
					"Felfedezett elemek {0}/{1}",
					"Ide írj az elemek szűréséhez",
					"Vég elemek",
					"Tipp",
					"Wiki",
					"Opciók",
					"Segítség",
					"Névjegy",
					"Húzza ide az elemeket a kombináláshoz",
					"Húzza ide az elemet az eltávolításhoz",
					"Segítség",
					"A négy alapelemmel kezdesz: tűz, levegő, víz és föld. Kombináld őket, az új elemek felfedezéséhez. A játéknak vége ha minden elemet felfedeztél.\n\n",
					"A bal felső panelről húzhatsz át elemeket a középső területre. Húzz egymásra két elemet a kombináláshoz. Néhány elem vég elem, amelyet már nem tudsz kombinálni, ezek a bal alsó panelon vannak és nem mozdíthatóak. Ha a bal felső panelon valamelyik elemre duplán kattintasz, akkor az hozzáadódik a kombinálható elemekhez.\n\n",
					"Az elem eltávolításához húzd be azt a szemetesbe. Minden elem eltávolításához duplán kattints a szemetesen. Úgy is törölhetsz elemeket, hogy kiválasztod őket az egérrel miközben nyomva tartod a CTRL billentyűt, majd lenyomod a Delete-t.\n\n",
					"Ha a középső panelon lévő elemeken duplán kattintasz, akkor megduplázhatod őket. Ha a középső panelon üres területen kattintasz duplán, a négy alapelemet hozod elő.\n\n",
					"Az Alchemy-ról",
					"Alchemy {0} for Windows\n",
					"Készítette: Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Látogasd meg a www.mariusbancila.ro weboldalt.\n",
					"Inspirálta az Android operációs rendszerre fejlesztett Alchemy, melyet Andrey Zaikin készített.",
					"Az összes elem mutatása",
					"Tippek",
					"Próbálj meg",
					"-t készíteni a következőből:",
					"Kattints ide a tipp ablak bezárásához",
					"Nyelv",
					"Nyelv kiválasztása",
					"{0} legyen az új nyelv",
					"Mentések",
					"Nyelv",
					"Beállítások",
					"Csalások",
					"Készítők",
					"Az aktuális állapot elmentésre kerül kilépésnél és betöltődik a játék indításánál.\n\nElmentheted és betöltheted az aktuális állapotot, vagy kezdhetsz új játékot.\n",
					"Mentés",
					"Betöltés",
					"Alaphelyzet",
					"Csak új elemek létrehozása (figyelmen kívül hagyja a már felfedezett elemeket)",
					"Kombinálás kijelöléssel (nem húzással, hanem az első majd a második elemre való kattintással kombinál)",
					"További opciók",
					"Arra készülsz, hogy töröld az jelenlegi játék állást. Biztosan ezt akarod?\n\nÚj játék indítása előtt ajánlott menteni a jelenlegi állapotot.\n\nÚj játék indítása?",
					"Idő megjelenítése (összes eltelt idő)",
					"Kattints a Törlés-re az összes törléséhez",
					"CTRL + kattintás az egérrel + Delete-vel törölhetsz elemeket",
					"Kattints kétszer egy elemre a megduplázásához",
					"Kattints kétszer az asztalra a négy alapelem hozzáadásához",
					"A Tovább gombbal érheted el a beállításokat",
					"Kattints kétszer egy elemre hogy a munka asztalra kerüljön",
					"Fogd és vidd módszerrel az asztalra tudod tenni az elemet",
					"Néhány elem nem kombinálható",
					"Írj be egy nevet a szűréshez",
					"Törlés",
					"Győzelem",
					"Gratulálok!",
					"Az összes lehetséges elemet megtaláltad!",
				};
				
				m_uiresources[Languages.Indexes.Indonesian] = new string[]
				{
					"Elemen Yang Sudah Ditemukan {0}/{1}",
					"Ketik Disini Untuk Memfilter Elemen",
					"Elemen Yang Sudah Tidak Bisa Digabung Lagi",
					"Petunjuk",
					"Wiki",
					"Opsi",
					"Bantuan",
					"Tentang",
					"Seret Disini Untuk Menggabung Elemen",
					"Seret Disini Untuk Menghapus",
					"Bantuan",
					"Kamu Mulai Dengan Empat Elemen Dasar: Api, Udara, Air, Tanah . Gabungkan Elemen Tersebut Untuk Mendapatkan Elemen Yang Baru, Game Akan Tamat Apabila Semua Elemen Telah Ditemukan\n\n",
					"Kamu Bisa Menyeret Elemen Dari Panel Kiri Ke Area Tengah. Seret Dua Elemen Untuk Menggabung Elemen Tersebut. Beberapa Elemen Ada Yang Tidak Bisa Digabung, Elemen Tersebut Tidak Bisa Digabung Dengan Yang Lain. Elemen Tersebut Ditandai Dengan Ikon Merah Kecil Dibawah Kanan Dan Tidak Bisa Diseret Ke Area Tengah. Kamu Juga Bisa Memindahkan Elemen Dari Panel Kiri Ke Area Tengah Dengan Mengklik Dua Kali Elemen Tersebut .\n\n",
					"Untuk Mengahpus Semua Elemen Dari Area Tengah Klik Dua Kali Pada Ikon Tong Sampah  . Kamu Juga Bisa Menghapus Elemen Dengan Mengklik Elemen Tersebut Lalu Tahan Tombol Ctrl sambil Menekan Tombol Delete\n\n",
					"Klik Dua Kali Pada Sebuah Elemen Di Area Tengah Untuk Menggandakan Elemen Tersebut . Klik Dua Kali Di Bagian Kosong Dari Area Tengah Untuk Memunculkan Empat Elemen Dasar.\n\n",
					"Tentang Alchemy",
					"Alchemy {0} for Windows\n",
					"Dibuat Oleh Marius Bancila\n",
					"Hak Cipta (c) 2010-2011 Marius Bancila\n",
					"Kunjungi www.mariusbancila.ro\n",
					"Terinspirasi Oleh Alchemy for Android Buatan Andrey Zaikin",
					"Tunjukan Semua Elemen Yang Tersedia",
					"Petunjuk",
					"Coba Buat",
					"Dari",
					"Klik Didalam Window Untuk Menutup Window Ini",
					"Bahasa",
					"Pilih Bahasa",
					"Pilih {0} Sebagai Bahasa Baru",
					"Simpan",
					"Bahasa",
					"Opsi",
					"Cheats",
					"Credits",
					"Perkembangan Game-mu Telah Tersimpan Secara Otomatis Saat Game Ditutup Dan Akan Dimuat Kembali Saat Dimainkan Kembali.\n\nKamu Bisa Menyimpan Dan Memuat Perkembangan Game Dari Dokemun Selain Yang Standar .\n\nKamu Juga Bisa Mengulang Seluruh Perkembangan Game-mu Dan Memulai Dari Awal.\n",
					"Simpan",
					"Muat",
					"Ulang",
					"Hanya Gabungkan Yang Baru (Abaikan Bila Kombinasi Telah Ditemukan)",
					"Klik Untuk Menggabung (Jangan Diseret, Klik Elemen Pertama Lalu Klik Elemen Kedua)",
					"Opsi",
					"Kamu Akan Menghapus Seluruh Perkembangan Game-mu. Apa Kau Yakin?\n\nDirekomendasikan Untuk Menyimpan Perkembangan Game-mu Sebelum Kamu Mengulang .\n\nApakah Kamu Akan Mengulang ?",
					"Waktu (total waktu yang terlewat)",
					"Klik Hapus Untuk Menghapus Semua",
					"Ctrl + Klik Kiri + Delete Untuk Menghapus Sebuah Elemen",
					"Klik Dua Kali Untuk Menggandakan Elemen Tersebut",
					"Klik Dua Kali Di Area Tengah Untuk Memunculkan Empat Elemen Dasar",
					"Gunakan tombol opsi Untuk Men-Setting",
					"Klik Dua Kali Untuk Meletakan Di Area Tengah",
					"Seret Dan Letak Di Area Tengah",
					"Beberapa Elemen Tidak Bisa Digabungkan",
					"Ketik Nama Untuk Menfilter Daftar",
					"Hapus",
					"Victory",
					"Selamat!",
					"Kamu Telah Menemukan Semua Elemen Yang Ada!",
				};
				
				m_uiresources[Languages.Indexes.Italian] = new string[]
				{
					"Elementi sbloccati {0}/{1}",
					"Scrivi qui per filtrare gli elementi",
					"Elementi terminali",
					"Aiuto",
					"Wiki",
					"Opzioni",
					"Guida",
					"Info su",
					"Trascina gli elementi qui per combinarli",
					"Trascina un elemento qui per rimuoverlo",
					"Guida",
					"Si inizia con quattro elementi di base: Fuoco, Aria, Acqua e Terra Combinali per ottenere nuovi elementi. Il gioco finisce quando hai sbloccato tutti gli elementi.\n\n",
					"Puoi trascinare gli elementi dal pannello di sinistra nell'area centrale. Combinali trascinandoli uno sopra l'altro. Alcuni elementi sono terminali, e non possono più essere combinati: essi vengono elencati in un pannello secondario e non possono essere trascinati. Puoi aggiungere elementi all'area di gioco anche facendo doppio clic su di essi.\n\n",
					"Per rimuovere un elemento dall'area di gioco trascinalo sul cestino, per rimuovere tutti gli elementi dall'area di gioco fai doppio clic sul cestino. Puoi anche rimuovere gruppi di elementi selezionandoli uno ad uno mentre tieni premuto il tasto CTRL, e rimuovendoli premendo CANC.\n\n",
					"Fai doppio clic su un elemento nell'area di gioco per duplicarlo, fai doppio clic su uno spazio vuoto nell'area di gioco per riportare in gioco i quattro elementi di base.\n\n",
					"Informazioni su Alchemy",
					"Alchemy {0} per Windows\n",
					"Scritto da Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Vienimi a trovare su www.mariusbancila.ro\n",
					"Ispirato da Alchemy for Android by Andrey Zaikin",
					"Mostra tutti gli elementi disponibili",
					"Aiuto",
					"Prova a ottenere",
					"Da",
					"Clicca all'interno per chiudere l'aiuto",
					"Lingua",
					"Seleziona lingua",
					"Seleziona {0} come nuova lingua",
					"Salva",
					"Lingua",
					"Opzioni",
					"Trucchi",
					"Riconoscimenti",
					"Il progresso di gioco viene salvato automaticamente quando chiudi il gioco e ricaricato quando lo lanci.\n\nPuoi memorizzare il progresso di gioco o caricarlo da un altro file.\n\nPuoi anche cancellare tutti i progressi e ripartire dall'inizio.\n",
					"Salva",
					"Carica",
					"Cancella tutto",
					"Combina solo nuovi (non ripresentare le combinazioni già ottenute)",
					"Combina cliccando (non trascinare, clicca sul primo e poi sul secondo elemento)",
					"Opzioni avanzate",
					"Stai per cancellare completamente i progressi di gioco. Confermi di volerlo fare?\n\nTi suggerisco di salvare i progressi in un file separato prima di cancellare tutto.\n\nVuoi ripartire da zero?",
					"Mostra cronometro (tempo di gioco totale)",
					"Click on Clear to delete all",
					"Ctrl + mouse click + Delete to delete an element",
					"Double click on element to double it",
					"Double click on desktop for basic elements",
					"Use button More for settings",
					"Double click to put on desktop",
					"Drag and drop to desktop",
					"Some elements cannot be combined",
					"Type a name to filter the list",
					"Clear",
					"Victory",
					"Congratulations!",
					"You have unlocked all the available elements!",
				};
				
				m_uiresources[Languages.Indexes.Polish] = new string[]
				{
					"Odblokowane elementy {0}/{1}",
					"Pisz tutaj, by filtrować elementy",
					"Elementy końcowe",
					"Podpowiedź",
					"Wiki",
					"Więcej",
					"Pomoc",
					"O grze",
					"Przeciągnij elementy tutaj, aby je połączyć",
					"Przeciągnij element tutaj, aby go usunąć",
					"Pomoc",
					"Zaczynasz z czterema podstawowymi żywiołami: ogniem, powietrzem, wodą i ziemią. Połącz je w celu uzyskania nowych elementów. Zakończysz grę, gdy odblokujesz wszystkie elementy.\n\n",
					"Możesz przeciągać elementy z panelu po lewej stronie do obszaru w centrum. Połóż dwa elementy na sobie, aby je połączyć. Niektóre elementy są końcowe, nie można ich więcej łączyć. Są one wyświetlane z ikoną blokady i nie mogą być przeciągane na obszar pulpitu. Można również dodawać na pulpit elementy z listy poprzez podwójne kliknięcie na nich.\n\n",
					"Aby usunąć wszystkie elementy z pulpitu, kliknij dwukrotnie na ikonie śmietnika. Można również usunąć elementy wybierając je za pomocą myszy, przytrzymując klawisz Ctrl, a następnie naciskając klawisz Delete.\n\n",
					"Kliknij dwukrotnie na elemencie z pulpitu, aby go podwoić. Kliknij dwukrotnie na pustym miejscu na pulpicie, by przywołać cztery podstawowe żywioły.\n\n",
					"O Alchemy",
					"Alchemy {0} dla Windows\n",
					"Stworzony przez Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Odwiedź stronę www.mariusbancila.ro\n",
					"Zainspirowany przez Alchemy dla Androida Andreya Zaikina",
					"Pokaż wszystkie dostępne elementy",
					"Podpowiedzi",
					"Spróbuj zrobić",
					"z",
					"Kliknij wewnątrz, aby zamknąć okno z podpowiedzią",
					"Język",
					"Wybierz język",
					"Wybierz {0} jako nowy język",
					"Zapisy",
					"Język",
					"Ustawienia",
					"Kody",
					"Podziękowania",
					"Twój postęp w grze jest zapisywany automatycznie po zamknięciu gry i wczytywany w czasie uruchomienia.\n\nMożesz również zapisać lub wczytać postęp do lub z pliku innego niż domyślny.\n\nMożesz również zresetować cały postęp i zacząć grę od nowa.\n",
					"Zapisz",
					"Wczytaj",
					"Resetuj",
					"Łącz tylko nowe (ignoruj już odkryte kombinacje)",
					"Kliknij, by połączyć (nie przeciągaj, kliknij pierwszy element, a następnie drugi)",
					"Więcej opcji",
					"Zamierzasz usunąć cały dotychczasowy postęp. Czy na pewno chcesz to zrobić?\n\nZaleca się zapisać bieżący postęp przed dokonaniem resetu.\n\nCzy chcesz zresetować?",
					"Wyświetlaj czas (całkowity czas gry)",
					"Kliknij Wyczyść, aby usunąć wszystkie",
					"Ctrl + kliknięcie myszy + Delete, aby usunąć element",
					"Kliknij dwukrotnie na elemencie, aby go podwoić",
					"Kliknij dwukrotnie na pulpicie, by stworzyć podstawowe żywioły",
					"Użyj przycisku Więcej, aby wejść w ustawienia",
					"Kliknij dwukrotnie, by umieścić na pulpicie",
					"Przeciągnij i upuść na pulpit",
					"Niektóre elementy nie mogą być połączone",
					"Wpisz nazwę, aby przefiltrować listę",
					"Wyczyść",
					"Zwycięstwo",
					"Gratulacje!",
					"Właśnie odblokowałeś wszystkie dostępne elementy!",
				};
				
				m_uiresources[Languages.Indexes.Portuguese] = new string[]
				{
					"Elementos destravados {0}/{1}",
					"Digite aqui para filtrar os elementos",
					"Elementos terminais",
					"Dica",
					"Wiki",
					"Mais",
					"Ajuda",
					"Sobre",
					"Arraste os elementos aqui para combinar",
					"Arraste os elementos aqui para remover",
					"Ajuda",
					"Você começa com quatro elementos básicos: fogo, ar, água e terra. Combine-os para obter novos elementos. Você finaliza o jogo quando destravar todos os elementos.\n\n",
					"Você pode arrastar elementos do painel esquerdo para dentro da área central. Arraste dois elementos juntos para combiná-los. Alguns elementos são terminais, eles não poderão mais ser combinados. Eles serão exibidos em um segundo painel e não poderão ser arrastados para a área de trabalho. Você também poderá adicionar elementos da lista para a área de trabalho clicando duas vezes nele.\n\n",
					"Para remover um elemento da área de trabalho arraste-o para cima da lixeira. Para remover todos os elementos da área de trabalho clique duas vezes na lixeira. Você também pode excluir elementos selecionando-os com o mouse enquanto pressiona a tecla Control (CTRL) e, em seguida, pressionando a tecla Delete (DEL).\n\n",
					"Clique duas vezes em um elemento na área de trabalho para duplicá-lo. Clique duas vezes em um espaço vazio na área de trabalho para trazer os quatro elementos básicos.\n\n",
					"Sobre o Alchemy",
					"Alchemy {0} para Windows\n",
					"Criado por Marius Bancila\n",
					"Todos os Direitos Reservados (R) 2010-2011 Marius Bancila\n",
					"Visite www.mariusbancila.ro\n",
					"Inspirado no Alchemy para Android do Andrey Zaikin",
					"Exibir todos os elementos disponíveis",
					"Dicas",
					"Tente criar",
					"a partir de",
					"Clique dentro para fechar a janela da dica",
					"Idioma",
					"Selecione o idioma",
					"Selecionar {0} como o novo idioma",
					"Jogos Salvos",
					"Idioma",
					"Configuração",
					"Cheats",
					"Créditos",
					"Seu progresso de jogo é salvo automaticamente quando você fecha o jogo e carregado quando você inicia.\n\nVocê pode armazenar ou carregar o progresso para ou de outro arquivo diferente do padrão.\n\nVocê também pode reiniciar todo o seu progresso e iniciar tudo novamente.\n",
					"Salvar",
					"Carregar",
					"Reiniciar",
					"Combinar somente novos elementos (ignorar combinações já descobertas)",
					"Selecionar para combinar (não arrastar, selecionar o 1º elemento e depois o 2º)",
					"Mais opções",
					"Você está prestes a apagar todo o seu progresso realizado. Você tem certeza que quer fazer isto?\n\nÉ recomendado que você salve o seu progresso atual antes de reiniciar.\n\nVocê gostaria de reiniciar?",
					"Exibir cronômetro (tempo total decorrido)",
					"Clique no Limpar para apagar todos",
					"Ctrl + Clique do mouse + Delete para apagar um elemento",
					"Clique duplo em um elemento para duplicá-lo",
					"Clique duplo na área de trabalho para obter os elementos básicos",
					"Use o botão Mais para configurações",
					"Clique duplo para colocá-lo na área de trabalho",
					"Arrastar e Soltar para a área de trabalho",
					"Alguns elementos não podem ser combinados",
					"Digite um nome para filtrar a lista",
					"Limpar",
					"Vitória",
					"Parabéns!",
					"Você destravou todos os elementos disponíveis!",
				};
				
				m_uiresources[Languages.Indexes.Romanian] = new string[]
				{
					"Elemente descoperite {0}/{1}",
					"Introduce nume pentru filtrare",
					"Elemente terminale",
					"Pont",
					"Wiki",
					"Alte",
					"Ajutor",
					"Despre",
					"Trage elemente aici pentru a le combina",
					"Trage elemente aici pentru a le sterge",
					"Ajutor",
					"Pornesti cu patru elemente de baza: pamant, apa, aer, foc. Combina-le pentru a obtine noi elemente. Termini cand descoperi toate elementele.\n\n",
					"Poti trage elemente din zona din stanga in zona centrala. Pune doua elemente unul peste altul pentru a le combina. Unele elemente sunt terminale, ele nu mai pot fi combinate. Acestea sunt afisate cu o icoana ce indica blocare si nu pot fi trase de aici in zona de lucru. Elemente neterminale pot fi de asemenea adaugate in zona de lucru cu dublu clic.\n\n",
					"Pentru a sterge toate elementele din zona de lucru fa un dublu clic pe cosul de gunoi. Se pot sterge elemente si selectandu-le cu mouseul tinand tasta Control apasata si apoi apasand tasta Delete.\n\n",
					"Pentru a duplica un element in zona de lucru fa un dublu clic pe el. Un dublu clic intr-o arie goala din zona de lucru va aduce acolo cele patru elemente primordiale.\n\n",
					"Despre Alchemy",
					"Alchemy {0} pentru Windows\n",
					"Creat de Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Viziteaza la www.mariusbancila.ro\n",
					"Inspirat din Alchemy pentru Android de Andrey Zaikin",
					"Afiseaza toate elementele disponibile",
					"Ponturi",
					"Incearca sa creezi",
					"din",
					"Click inauntru pentru a inchide fereastra",
					"Limba",
					"Selecteaza limba",
					"Selecteaza {0} ca limba noua",
					"Salvari",
					"Limba",
					"Setari",
					"Ponturi",
					"Credite",
					"Progresul in joc este salvat automat cand inchizi jocul si reincarcat cand pornesti jocul.\n\nPoti salva sau incarca progresul in alt fisier decat cel implicit.\n\nPoti de asemenea sterge progresul actual si reincepe de la zero.\n",
					"Salveaza",
					"Incarca",
					"Sterge",
					"Doar combinatii noi (ignora cele descoperite deja)",
					"Atinge pentru a combina (nu trage, atinge primul element apoi al doilea)",
					"Alte optiuni",
					"Esti pe cale sa stergi intregul progres de pana acum. Esti sigur ca vrei sa faci acest lucru?\n\nEste recomandat sa salvezi progresul inainte de a sterge tot.\n\nDoresti sa stergi tot?",
					"Afiseaza timpul (total trecut de la inceput)",
					"Clic pe Sterge pentru a sterge toate elementele.",
					"Ctrl + clic + Delete pentru a sterge un element",
					"Clic dublu pe un element pentru a-l dubla",
					"Clic dublu pe desktop pentru a aduce elementele primare",
					"Foloseste butonul Alte pentru setari",
					"Clic dublu pentru a pune pe desktop",
					"Trage elemente pe desktop",
					"Unele elemente nu pot fi combinate",
					"Introdu un nume pentru filtrare",
					"Sterge",
					"Victorie",
					"Felicitari!",
					"Ai descoperit toate elementele disponibile!",
				};
				
				m_uiresources[Languages.Indexes.Slovak] = new string[]
				{
					"Dostupné objavy {0}/{1}",
					"Vyhladajte element",
					"Terminal elements",
					"Nápoveda",
					"Wiki",
					"Viac",
					"Pomoc",
					"O programe",
					"Sem pretiahnite pre kombinovanie",
					"Sem pretiahnite pre vymazanie",
					"Pomoc",
					"Začínate so štyrmi základnými elementami: ohňom, vzduchom, vodou a zemou. Ich kombináciou získate ďalšie elementy. Hra končí keď sú objavené všetky.\n\n",
					"Môžete pretiahnuť elementy z ľavého panela do strednej časti (pracovnú plochu) Pretiehnite dva elementy na seba a tým ich skombinujete. Niektoré elementy sú však konečné a nemožno ich ďalej kombinovať. Sú zobrazené s blokovacou ikonkou vpravo dole a nejdú pretiahnuť na pracovnú plochu. Element je tiež možné pridať dvojklikom v zozname.\n\n",
					"Pre odstránenie elementu ho pretiahnite do koša. Pre odstránenie všetkých elementov z pracovnej plochy kliknite na kôš (vymazať). Elementy môžete tiež vymazať vybraním myšou spolu s klávesou CTRL a potom stlačiť klávesu Delete.\n\n",
					"Dvojklik na element na pracovnej ploche pre jeho zdvojenie. Dvojklikom na prázdne miesto na pracovnej ploche pre pridanie štyroch základných elementov.\n\n",
					"O Alchemy",
					"Alchemy {0} pre Windows\n",
					"Autor - Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Navštívte www.mariusbancila.ro\n",
					"Inšpirované Alchemy pre Android od Andrey Zaikin",
					"Ukáž všetky elementy",
					"Rada",
					"Skúste vytvoriť",
					"z",
					"Kliknite do plochy pre zatvorenie tohoto okna",
					"Jazyk",
					"Zvoľte jazyk",
					"Zvoľte {0} ako nový jazyk",
					"Uložené",
					"Jazyk",
					"Nastavenia",
					"Cheaty",
					"Kredity",
					"Vaša hra je automaticky uložená keď skončíte a načítaná pri štarte\n\nJe možné hru uložiť a načítať aj z iného než základného súboru.\n\nMôžete tiež hru zresetovať a začať všetko od začiatku.\n",
					"Uložiť",
					"Načítať",
					"Reset",
					"Kombinovať iba nové (ignorovať už objavené kombinácie)",
					"Kombinovať kliknutím (nepretahovať, kliknúť na prvý a potom druhý element",
					"Viac možností",
					"Naozaj chcete aby sa váš súčasný pokrok kompletne vymazal?\n\nPred resetom je doporučené najprv uložiť aktuálny stav.\n\nSkutočne zresetovať?",
					"Zobraziť časomieru (celkový uplynutý čas)",
					"Kliknite na Vymazať pre vymazanie všetkého",
					"Ctrl + klik + Delete pre vymazanie elementu",
					"Dvojklik na element pre zdvojenie",
					"Dvojklik na plochu pre pridanie základných elementov",
					"Použite tlačítko Viac pre nastavenia",
					"Dvojklik pre pridanie na plochu",
					"Chyťte a pretiahnite na plochu",
					"Niektoré elemnety nemožno kombinovať",
					"Napíšte meno pre filtrovanie zoznamu",
					"Vymazať",
					"Víťazstvo",
					"Gratulujeme!",
					"Máte vynájdené všetky dostupné elementy!",
				};
				
				m_uiresources[Languages.Indexes.Spanish] = new string[]
				{
					"Elementos desbloqueados{0}/{1}",
					"Escribe aquí para filtrar elementos",
					"Elementos terminales",
					"Pista",
					"Wiki",
					"Más",
					"Ayuda",
					"Acerca de",
					"Arrastra elementos acá para combinarlos",
					"Arrastra elementos acá para eliminarlos",
					"Ayuda",
					"Inicia con los 4 elementos básicos: fuego, aire, agua y tierra. Combínalos para obtener nuevos lementos. Has terminado cuando descubras todos los elementos.\n\n",
					"Puedes arrastrar elementos del panel izquierdo al área central. Arrastra dos elementos para combinarlos. Algunos elementos son terminales, esos ya no pueden ser combinados. Se ven con un ícono de bloqueo y no pueden ser arrastrados hacia el área de escritorio. Puedes también añadir elementos de la lista al escritorio haciendo doble clic en ellos.\n\n",
					"Para eliminar todos los elementos del escritorio, haz doble clic en el basurero. También puedes eliminar elementos seleccionándolos con el ratón mientras mantienes presionada la tecla Control y luego presionando Delete.\n\n",
					"Haz doble clic a un elemento en el escritorio para que se multiplique. Haz doble clic en un espacio vacio para crear los cuatro elementos básicos.\n\n",
					"Acerca de Alchemy",
					"Alchemy {0} para Windows\n",
					"Creado por Marius Bancila\n",
					"Copyright (c) 2010-2011 Marius Bancila\n",
					"Visíta www.mariusbancila.ro\n",
					"Inspirado en el juego Alchemy para Android de Andrey Zaikin",
					"Muestra todos los elementos disponibles.",
					"Pistas",
					"Intenta hacer",
					"De",
					"Haz clic en esta ventana para cerrarla",
					"Lenguaje",
					"Selecciona lenguaje",
					"Selecciona {0} como nuevo lenguaje",
					"Guardar",
					"Lenguaje",
					"Configuración",
					"Trucos",
					"Créditos",
					"El progreso de tu juego es guardado automáticamente cuando cierras el juego y es cargado couando lo inicias.\n\n Puedes guardar o cargar el progreso de o hacia otro archivo distinto del que está por defecto.\n\n También puedes resetear todo tu progreso y comenzar de nuevo.\n",
					"Guardar",
					"Cargar",
					"Resetear",
					"Combinar solamente nuevos(ignorar las combinaciones ya descubiertas)",
					"Clic para combinar(sin arrastrar, clic en el 1er elemento y luego en el 2º)",
					"Más opciones",
					" Estás a punto de borrar todo tu progreso hasta ahora. Estás seguro que deseas hacer eso?\n\nIt es recomendable que guardes tu progreso antes de resetearlo.\n\nQuieres resetearlo?",
					"Mostrar contador (tiempo total transcurrido)",
					"Clic en Clear para eliminarlo todo",
					"Ctrl + clic + Delete para eliminar un elemento.",
					"Doble clic en un elemento para duplicarlo.",
					"Doble clic en el escritorio para los elemntos básicos.",
					"usa el botón más para configurar",
					"Doble clic para llevarlo al escritorio",
					"Arrastra y déjalo sobre el escritorio.",
					"Algunos elemntos no pueden ser combinados.",
					"Escribe un nombre para filtrarlo de la lista.",
					"Limpiar",
					"Victoria",
					"¡Felicidades!",
					"¡Has desbloqueado todos los elementos disponibles!",
				};
				
			
			}
		}
	}
}